import { db } from "@workspace/db";
import {
  activityTable,
  fulfillmentExceptionsTable,
  inventoryNodesTable,
  orderLinesTable,
  ordersTable,
  settlementBatchesTable,
  timelineEventsTable,
  vendorSubOrdersTable,
  vendorsTable,
} from "@workspace/db";

const hoursAgo = (hours: number) => new Date(Date.now() - hours * 60 * 60 * 1000);

export async function seedCommerceData(): Promise<void> {
  const existing = await db.select({ id: ordersTable.id }).from(ordersTable).limit(1);
  if (existing.length > 0) return;

  await db.insert(vendorsTable).values([
    {
      id: "vendor-aurora",
      name: "Aurora Home",
      category: "Home & Living",
      status: "active",
      orders: 142,
      payable: 847500,
      health: 96,
    },
    {
      id: "vendor-verdant",
      name: "Verdant & Co.",
      category: "Wellness",
      status: "active",
      orders: 98,
      payable: 562000,
      health: 91,
    },
    {
      id: "vendor-kora",
      name: "Kora Studio",
      category: "Accessories",
      status: "review",
      orders: 64,
      payable: 318500,
      health: 78,
    },
  ]).onConflictDoNothing();

  await db.insert(ordersTable).values([
    {
      id: "ORD-10048",
      customerName: "Ayesha Khan",
      customerEmail: "ayesha.khan@example.com",
      status: "in_fulfillment",
      paymentStatus: "captured",
      fulfillmentStatus: "partially_shipped",
      total: 24800,
      currency: "PKR",
      vendorCount: 2,
      itemCount: 3,
      createdAt: hoursAgo(2),
      returnWindow: "Eligible until 06 Oct",
      exception: "Shipment stalled at Lahore hub",
    },
    {
      id: "ORD-10047",
      customerName: "Hamza Siddiqui",
      customerEmail: "hamza.siddiqui@example.com",
      status: "delivered",
      paymentStatus: "captured",
      fulfillmentStatus: "delivered",
      total: 15600,
      currency: "PKR",
      vendorCount: 1,
      itemCount: 2,
      createdAt: hoursAgo(5),
      returnWindow: "Eligible until 12 Oct",
      exception: null,
    },
    {
      id: "ORD-10046",
      customerName: "Mariam Raza",
      customerEmail: "mariam.raza@example.com",
      status: "payment_pending",
      paymentStatus: "requires_action",
      fulfillmentStatus: "awaiting_payment",
      total: 9800,
      currency: "PKR",
      vendorCount: 1,
      itemCount: 1,
      createdAt: hoursAgo(7),
      returnWindow: "Starts on delivery",
      exception: null,
    },
    {
      id: "ORD-10045",
      customerName: "Bilal Ahmed",
      customerEmail: "bilal.ahmed@example.com",
      status: "on_hold",
      paymentStatus: "captured",
      fulfillmentStatus: "allocation_failed",
      total: 43200,
      currency: "PKR",
      vendorCount: 2,
      itemCount: 4,
      createdAt: hoursAgo(11),
      returnWindow: "Starts on delivery",
      exception: "Inventory shortfall at Karachi node",
    },
    {
      id: "ORD-10044",
      customerName: "Noor Fatima",
      customerEmail: "noor.fatima@example.com",
      status: "settlement_ready",
      paymentStatus: "captured",
      fulfillmentStatus: "delivered",
      total: 30500,
      currency: "PKR",
      vendorCount: 1,
      itemCount: 2,
      createdAt: hoursAgo(18),
      returnWindow: "Closed",
      exception: null,
    },
  ]).onConflictDoNothing();

  await db.insert(vendorSubOrdersTable).values([
    {
      id: "VSO-10048-A",
      orderId: "ORD-10048",
      vendorName: "Aurora Home",
      status: "shipped",
      itemCount: 2,
      fulfillmentNode: "Lahore Hub",
      shipmentStatus: "stalled",
    },
    {
      id: "VSO-10048-B",
      orderId: "ORD-10048",
      vendorName: "Verdant & Co.",
      status: "delivered",
      itemCount: 1,
      fulfillmentNode: "Islamabad Node",
      shipmentStatus: "delivered",
    },
    {
      id: "VSO-10047-A",
      orderId: "ORD-10047",
      vendorName: "Aurora Home",
      status: "delivered",
      itemCount: 2,
      fulfillmentNode: "Lahore Hub",
      shipmentStatus: "delivered",
    },
    {
      id: "VSO-10045-A",
      orderId: "ORD-10045",
      vendorName: "Kora Studio",
      status: "allocation_failed",
      itemCount: 2,
      fulfillmentNode: "Karachi Node",
      shipmentStatus: "not_created",
    },
    {
      id: "VSO-10045-B",
      orderId: "ORD-10045",
      vendorName: "Verdant & Co.",
      status: "ready_to_fulfill",
      itemCount: 2,
      fulfillmentNode: "Islamabad Node",
      shipmentStatus: "not_created",
    },
  ]).onConflictDoNothing();

  await db.insert(orderLinesTable).values([
    {
      id: "LINE-10048-1",
      orderId: "ORD-10048",
      sku: "AUR-LMP-042",
      title: "Luma table lamp",
      vendorName: "Aurora Home",
      quantity: 1,
      unitPrice: 12800,
      status: "shipped",
    },
    {
      id: "LINE-10048-2",
      orderId: "ORD-10048",
      sku: "AUR-TRAY-018",
      title: "Hand-thrown serving tray",
      vendorName: "Aurora Home",
      quantity: 1,
      unitPrice: 7200,
      status: "shipped",
    },
    {
      id: "LINE-10048-3",
      orderId: "ORD-10048",
      sku: "VER-TEA-011",
      title: "Mountain mint tea set",
      vendorName: "Verdant & Co.",
      quantity: 1,
      unitPrice: 4800,
      status: "delivered",
    },
    {
      id: "LINE-10045-1",
      orderId: "ORD-10045",
      sku: "KOR-BAG-006",
      title: "Mosaic leather tote",
      vendorName: "Kora Studio",
      quantity: 2,
      unitPrice: 15600,
      status: "allocation_failed",
    },
    {
      id: "LINE-10045-2",
      orderId: "ORD-10045",
      sku: "VER-OIL-021",
      title: "Rosewood body oil",
      vendorName: "Verdant & Co.",
      quantity: 2,
      unitPrice: 6000,
      status: "reserved",
    },
  ]).onConflictDoNothing();

  await db.insert(timelineEventsTable).values([
    {
      id: "TIMELINE-10048-1",
      orderId: "ORD-10048",
      label: "Payment captured",
      detail: "PKR 24,800 captured through the payment gateway",
      occurredAt: hoursAgo(2),
      tone: "success",
    },
    {
      id: "TIMELINE-10048-2",
      orderId: "ORD-10048",
      label: "Order split",
      detail: "Created two vendor sub-orders across three lines",
      occurredAt: hoursAgo(1.8),
      tone: "info",
    },
    {
      id: "TIMELINE-10048-3",
      orderId: "ORD-10048",
      label: "Carrier exception",
      detail: "No movement recorded at Lahore hub for 26 hours",
      occurredAt: hoursAgo(0.5),
      tone: "warning",
    },
    {
      id: "TIMELINE-10045-1",
      orderId: "ORD-10045",
      label: "Inventory allocation failed",
      detail: "Karachi Node could not reserve two units of KOR-BAG-006",
      occurredAt: hoursAgo(10),
      tone: "danger",
    },
  ]).onConflictDoNothing();

  await db.insert(activityTable).values([
    {
      id: "ACT-001",
      type: "exception",
      title: "Shipment exception opened",
      detail: "ORD-10048 has not moved at Lahore Hub for 26 hours",
      occurredAt: hoursAgo(0.5),
      tone: "warning",
      orderId: "ORD-10048",
    },
    {
      id: "ACT-002",
      type: "order",
      title: "Order split completed",
      detail: "ORD-10048 routed to Aurora Home and Verdant & Co.",
      occurredAt: hoursAgo(1.8),
      tone: "info",
      orderId: "ORD-10048",
    },
    {
      id: "ACT-003",
      type: "settlement",
      title: "Settlement batch ready",
      detail: "Batch SET-2409 is eligible for finance review",
      occurredAt: hoursAgo(3),
      tone: "success",
      orderId: null,
    },
    {
      id: "ACT-004",
      type: "inventory",
      title: "Reservation nearing expiry",
      detail: "Four units at Karachi Node expire within 45 minutes",
      occurredAt: hoursAgo(4),
      tone: "warning",
      orderId: null,
    },
    {
      id: "ACT-005",
      type: "return",
      title: "Return window closed",
      detail: "ORD-10044 is now settlement eligible",
      occurredAt: hoursAgo(8),
      tone: "success",
      orderId: "ORD-10044",
    },
  ]).onConflictDoNothing();

  await db.insert(inventoryNodesTable).values([
    {
      id: "node-lahore",
      name: "Lahore Hub",
      region: "Punjab",
      available: 1248,
      reserved: 182,
      health: "healthy",
    },
    {
      id: "node-islamabad",
      name: "Islamabad Node",
      region: "Capital",
      available: 824,
      reserved: 96,
      health: "healthy",
    },
    {
      id: "node-karachi",
      name: "Karachi Node",
      region: "Sindh",
      available: 412,
      reserved: 88,
      health: "watch",
    },
  ]).onConflictDoNothing();

  await db.insert(fulfillmentExceptionsTable).values([
    {
      id: "EXC-001",
      orderId: "ORD-10048",
      title: "Shipment stalled",
      detail: "No carrier movement recorded at Lahore Hub",
      severity: "high",
      age: "26h",
      owner: "Operations",
      status: "open",
    },
    {
      id: "EXC-002",
      orderId: "ORD-10045",
      title: "Inventory allocation failed",
      detail: "Kora Studio has no available stock at Karachi Node",
      severity: "critical",
      age: "10h",
      owner: "Kora Studio",
      status: "open",
    },
    {
      id: "EXC-003",
      orderId: "ORD-10041",
      title: "Return inspection overdue",
      detail: "Inspection has been pending for more than two business days",
      severity: "medium",
      age: "2d",
      owner: "Returns Desk",
      status: "open",
    },
  ]).onConflictDoNothing();

  await db.insert(settlementBatchesTable).values([
    {
      id: "SET-2409",
      label: "September 24 morning run",
      amount: 1728000,
      vendorCount: 8,
      status: "ready_for_review",
      date: "24 Sep 2026",
    },
    {
      id: "SET-2408",
      label: "September 21 completed",
      amount: 2145000,
      vendorCount: 11,
      status: "reconciled",
      date: "21 Sep 2026",
    },
    {
      id: "SET-2407",
      label: "September 18 completed",
      amount: 1862000,
      vendorCount: 9,
      status: "reconciled",
      date: "18 Sep 2026",
    },
  ]).onConflictDoNothing();
}